version: '3'

services:
  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
    environment:
      - SCYLLA_CLUSTER_NAME=scylladb-iot-demo
      - SCYLLA_DC=datacenter1
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
      - SCYLLA_RPC_ADDRESS=0.0.0.0
      - SCYLLA_NUM_TOKENS=256
      - SCYLLA_AUTO_BOOTSTRAP=true

  sensor-app:
    image: ashok-demos/scylladb-iot-demo
    depends_on:
      - scylla
    environment:
      - SCYLLA_CONTACT_POINTS=scylla
      - SCYLLA_DC=datacenter1
      - SCYLLA_PORT=9042
      - SCYLLA_KEY_SPACE=sensor_db