spring:
  cassandra:
    contact-points: {SCYLLA_CONTACT_POINTS}
    port: 9042
    keyspace-name: sensor_db
    local-datacenter: datacenter1
    schema-action: none
    username: cassandra
    password: cassandra
